// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job.sql

package repository

import (
	"context"
)

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1 AND user_id= $2
`

type DeleteJobParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.Exec(ctx, deleteJob, arg.ID, arg.UserID)
	return err
}

const getJobs = `-- name: GetJobs :many
SELECT id, position, company, user_id FROM jobs
WHERE user_id = $1
`

func (q *Queries) GetJobs(ctx context.Context, userID int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Company,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (position, company, user_id)
VALUES ($1, $2, $3)
RETURNING id, position, company, user_id
`

type InsertJobParams struct {
	Position string `json:"position"`
	Company  string `json:"company"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob, arg.Position, arg.Company, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Company,
		&i.UserID,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET position = $2, company = $3
WHERE id = $1 AND user_id = $4
RETURNING id, position, company, user_id
`

type UpdateJobParams struct {
	ID       int32  `json:"id"`
	Position string `json:"position"`
	Company  string `json:"company"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Position,
		arg.Company,
		arg.UserID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Company,
		&i.UserID,
	)
	return i, err
}
