// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Job struct {
	ID       int32  `json:"id"`
	Position string `json:"position"`
	Company  string `json:"company"`
}

type User struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	HashPassword string `json:"hash_password"`
}
