// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package respository

import (
	"context"
)

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (position, company)
VALUES ($1, $2)
RETURNING id, position, company
`

type InsertJobParams struct {
	Position string
	Company  string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob, arg.Position, arg.Company)
	return err
}
