// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package respository

import (
	"context"
)

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (position, company)
VALUES ($1, $2)
RETURNING id, position, company
`

type InsertJobParams struct {
	Position string
	Company  string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob, arg.Position, arg.Company)
	var i Job
	err := row.Scan(&i.ID, &i.Position, &i.Company)
	return i, err
}
