// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package respository

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, hash_password)
VALUES ($1, $2)
RETURNING username, hash_password
`

type InsertUserParams struct {
	Username     string
	HashPassword string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Username, arg.HashPassword)
	var i User
	err := row.Scan(&i.Username, &i.HashPassword)
	return i, err
}
